"""astrapi_mirror.modules.debian._seed – Initiale Repo-Daten aus refrapt-Config.

Wird beim ersten Start automatisch eingespielt wenn die Datenbank leer ist.
"""

_REPOS: list[dict] = [
    # ── Debian Official ───────────────────────────────────────────────────────
    {
        "id": "debian-bookworm",
        "label": "Debian Bookworm",
        "provider_group": "Debian",
        "url": "http://deb.debian.org/debian",
        "repo_type": "deb",
        "suites": ["bookworm", "bookworm-updates", "bookworm-proposed-updates", "bookworm-backports"],
        "components": ["main", "contrib", "non-free", "non-free-firmware"],
        "architectures": ["amd64", "arm64"],
        "is_flat": False,
        "enabled": True,
    },
    {
        "id": "debian-trixie",
        "label": "Debian Trixie",
        "provider_group": "Debian",
        "url": "http://deb.debian.org/debian",
        "repo_type": "deb",
        "suites": ["trixie", "trixie-updates", "trixie-proposed-updates", "trixie-backports"],
        "components": ["main", "contrib", "non-free", "non-free-firmware"],
        "architectures": ["amd64", "arm64"],
        "is_flat": False,
        "enabled": True,
    },
    {
        "id": "debian-security-bookworm",
        "label": "Debian Security (Bookworm)",
        "provider_group": "Debian",
        "url": "http://security.debian.org/debian-security",
        "repo_type": "deb",
        "suites": ["bookworm-security"],
        "components": ["main", "contrib", "non-free"],
        "architectures": ["amd64", "arm64"],
        "is_flat": False,
        "enabled": True,
    },
    {
        "id": "debian-security-trixie",
        "label": "Debian Security (Trixie)",
        "provider_group": "Debian",
        "url": "http://security.debian.org/debian-security",
        "repo_type": "deb",
        "suites": ["trixie-security"],
        "components": ["main", "contrib", "non-free"],
        "architectures": ["amd64", "arm64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── PostgreSQL ────────────────────────────────────────────────────────────
    {
        "id": "pgadmin4",
        "label": "pgAdmin 4",
        "provider_group": "PostgreSQL",
        "url": "https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/bookworm",
        "repo_type": "deb",
        "suites": ["pgadmin4"],
        "components": ["main"],
        "architectures": ["amd64", "all"],
        "is_flat": False,
        "enabled": True,
    },
    {
        "id": "postgresql-pgdg",
        "label": "PostgreSQL PGDG",
        "provider_group": "PostgreSQL",
        "url": "http://apt.postgresql.org/pub/repos/apt",
        "repo_type": "deb",
        "suites": ["bookworm-pgdg"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Caddy ─────────────────────────────────────────────────────────────────
    {
        "id": "caddy",
        "label": "Caddy",
        "provider_group": "Web",
        "url": "https://dl.cloudsmith.io/public/caddy/stable/deb/debian",
        "repo_type": "deb",
        "suites": ["any-version"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Redis ─────────────────────────────────────────────────────────────────
    {
        "id": "redis",
        "label": "Redis",
        "provider_group": "Datenbanken",
        "url": "https://packages.redis.io/deb",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["main"],
        "architectures": ["amd64", "all"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Proxmox ───────────────────────────────────────────────────────────────
    {
        "id": "proxmox-pve",
        "label": "Proxmox VE",
        "provider_group": "Proxmox",
        "url": "http://download.proxmox.com/debian/pve",
        "repo_type": "deb",
        "suites": ["bookworm", "trixie"],
        "components": ["pve-no-subscription"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    {
        "id": "proxmox-pbs",
        "label": "Proxmox Backup Server",
        "provider_group": "Proxmox",
        "url": "http://download.proxmox.com/debian/pbs",
        "repo_type": "deb",
        "suites": ["bookworm", "trixie"],
        "components": ["pbs-no-subscription"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── NodeJS ────────────────────────────────────────────────────────────────
    {
        "id": "nodejs-20",
        "label": "NodeJS 20.x",
        "provider_group": "NodeJS",
        "url": "https://deb.nodesource.com/node_20.x",
        "repo_type": "deb",
        "suites": ["nodistro"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    {
        "id": "nodejs-22",
        "label": "NodeJS 22.x",
        "provider_group": "NodeJS",
        "url": "https://deb.nodesource.com/node_22.x",
        "repo_type": "deb",
        "suites": ["nodistro"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Monitoring / Metrics ──────────────────────────────────────────────────
    {
        "id": "grafana",
        "label": "Grafana",
        "provider_group": "Monitoring",
        "url": "https://apt.grafana.com",
        "repo_type": "deb",
        "suites": ["stable"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    {
        "id": "influxdb",
        "label": "InfluxDB",
        "provider_group": "Monitoring",
        "url": "https://repos.influxdata.com/debian",
        "repo_type": "deb",
        "suites": ["stable"],
        "components": ["main"],
        "architectures": ["amd64", "arm64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Media / Streaming ─────────────────────────────────────────────────────
    {
        "id": "jellyfin",
        "label": "Jellyfin",
        "provider_group": "Media",
        "url": "https://repo.jellyfin.org/debian",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Webserver ─────────────────────────────────────────────────────────────
    {
        "id": "nginx",
        "label": "nginx (mainline)",
        "provider_group": "Web",
        "url": "http://nginx.org/packages/mainline/debian",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["nginx"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── PHP / Apache ──────────────────────────────────────────────────────────
    {
        "id": "php-sury",
        "label": "PHP (Sury)",
        "provider_group": "PHP",
        "url": "https://packages.sury.org/php/",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    {
        "id": "apache2-sury",
        "label": "Apache2 (Sury)",
        "provider_group": "PHP",
        "url": "https://packages.sury.org/apache2",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── IoT / MQTT ────────────────────────────────────────────────────────────
    {
        "id": "mosquitto",
        "label": "Mosquitto (MQTT)",
        "provider_group": "IoT",
        "url": "https://repo.mosquitto.org/debian",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["main"],
        "architectures": ["amd64", "all"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Microsoft ─────────────────────────────────────────────────────────────
    {
        "id": "vscode",
        "label": "VS Code",
        "provider_group": "Microsoft",
        "url": "https://packages.microsoft.com/repos/vscode",
        "repo_type": "deb",
        "suites": ["stable"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Java ──────────────────────────────────────────────────────────────────
    {
        "id": "zulu-jdk",
        "label": "Azul Zulu JDK",
        "provider_group": "Java",
        "url": "https://repos.azul.com/zulu/deb/",
        "repo_type": "deb",
        "suites": ["stable"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Docker ────────────────────────────────────────────────────────────────
    {
        "id": "docker",
        "label": "Docker",
        "provider_group": "Container",
        "url": "https://download.docker.com/linux/debian",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["stable"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Raspberry Pi ─────────────────────────────────────────────────────────
    {
        "id": "raspberrypi",
        "label": "Raspberry Pi",
        "provider_group": "ARM",
        "url": "http://archive.raspberrypi.org/debian/",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["main"],
        "architectures": ["arm64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Python ────────────────────────────────────────────────────────────────
    {
        "id": "python312",
        "label": "Python 3.12 (Backport)",
        "provider_group": "Python",
        "url": "http://deb.pascalroeleven.nl/python3.12",
        "repo_type": "deb",
        "suites": ["bookworm-backports"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    {
        "id": "python313",
        "label": "Python 3.13 (Backport)",
        "provider_group": "Python",
        "url": "http://deb.pascalroeleven.nl/python3.13",
        "repo_type": "deb",
        "suites": ["bookworm-backports"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── MariaDB ───────────────────────────────────────────────────────────────
    {
        "id": "mariadb",
        "label": "MariaDB 12.0",
        "provider_group": "Datenbanken",
        "url": "https://mirror.mariadb.org/repo/12.0.1/debian",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Sicherheit / Auth ─────────────────────────────────────────────────────
    {
        "id": "lldap",
        "label": "LLDAP",
        "provider_group": "Security",
        "url": "http://download.opensuse.org/repositories/home:/Masgalor:/LLDAP/Debian_12/",
        "repo_type": "deb",
        "suites": [],
        "components": [],
        "architectures": ["amd64"],
        "is_flat": True,
        "enabled": True,
    },
    {
        "id": "crowdsec",
        "label": "CrowdSec",
        "provider_group": "Security",
        "url": "https://packagecloud.io/crowdsec/crowdsec/debian/",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    {
        "id": "vaultwarden",
        "label": "Vaultwarden",
        "provider_group": "Security",
        "url": "https://packagecloud.io/dionysius/vaultwarden/debian/",
        "repo_type": "deb",
        "suites": ["bookworm"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
    # ── Heckel ────────────────────────────────────────────────────────────────
    {
        "id": "heckel",
        "label": "Heckel (ntfy)",
        "provider_group": "Tools",
        "url": "https://archive.heckel.io/apt",
        "repo_type": "deb",
        "suites": ["debian"],
        "components": ["main"],
        "architectures": ["amd64"],
        "is_flat": False,
        "enabled": True,
    },
]


def auto_seed(store) -> None:
    """Befüllt den Store mit den initialen Repos, wenn er leer ist."""
    if store.list():
        return
    for repo in _REPOS:
        repo_id = repo.pop("id")
        store.create(repo_id, repo)
