"""astrapi_mirror.modules.debian.engine – Kernlogik für Debian-Mirror.

Zuständig für:
- refrapt-Config-Generierung aus DB-Einträgen
- Vollständigkeits-Validierung nach dem Sync
- sources.list-Snippet-Generierung für Clients
"""
from __future__ import annotations

import email.utils
import logging
import re
from pathlib import Path
from urllib.parse import urlparse

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# refrapt-Config-Generierung
# ---------------------------------------------------------------------------

def _global_settings() -> dict[str, str]:
    """Liest globale refrapt-Settings aus der Settings-Registry."""
    from astrapi_core.ui.settings_registry import get_module
    from astrapi_mirror._paths import mirror_path, skel_path, var_path

    def _get(key: str, default: str) -> str:
        return get_module("debian", key, default=default)

    return {
        "mirrorPath": f'"{mirror_path()}"',
        "skelPath": f'"{skel_path()}"',
        "varPath": f'"{var_path()}"',
        "threads": _get("threads", "4"),
        "limitRate": _get("limit_rate", "200m"),
        "language": f'"{_get("language", "de_DE, en")}"',
        "contents": _get("contents", "True"),
        "noCheckCertificate": _get("no_check_cert", "False"),
        "logLevel": "INFO",
    }


def _repo_deb_lines(repo: dict) -> list[str]:
    """Erzeugt die deb-Zeilen für einen Repo-Eintrag."""
    t = repo.get("repo_type", "deb")
    url = (repo.get("url") or "").rstrip("/")
    archs = [a.strip() for a in (repo.get("architectures") or []) if a.strip()]
    arch_tag = f"[arch={','.join(archs)}]" if archs else ""

    if repo.get("is_flat"):
        return [f"{t} {arch_tag} {url}/".strip()]

    lines = []
    suites = [s.strip() for s in (repo.get("suites") or []) if s.strip()]
    components = " ".join(c.strip() for c in (repo.get("components") or []) if c.strip())
    for suite in suites:
        parts = [t]
        if arch_tag:
            parts.append(arch_tag)
        parts += [url, suite]
        if components:
            parts.append(components)
        lines.append(" ".join(parts))
    return lines


def generate_refrapt_config(repos: list[dict]) -> str:
    """Erzeugt vollständige refrapt.conf aus DB-Einträgen."""
    lines = ["## Generated by astrapi-mirror – do not edit manually ##", ""]

    for key, val in _global_settings().items():
        lines.append(f"set {key} = {val}")

    lines.append("")
    lines.append("## Repositories ##")

    for repo in repos:
        if not repo.get("enabled", True):
            continue
        label = repo.get("label") or repo.get("id", "")
        if label:
            lines.append(f"# {label}")
        for deb_line in _repo_deb_lines(repo):
            lines.append(deb_line)
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Validierung
# ---------------------------------------------------------------------------

def _host_path_from_url(url: str) -> str:
    """Gibt 'hostname/pfad' aus einer URL zurück."""
    p = urlparse(url)
    return (p.hostname or "") + p.path.rstrip("/")


_ARCH_IN_PATH = re.compile(r'(?:^|/)binary-([^/]+)/')
_ARCH_IN_NAME = re.compile(r'(?:^|/)Contents-([a-zA-Z0-9_]+)')
_COMPONENT_PREFIX = re.compile(r'^([^/]+)/')


def _should_skip(
    filename: str,
    arch_set: set[str] | None,
    component_set: set[str] | None,
    include_sources: bool,
) -> bool:
    """True wenn die Datei aufgrund der Repo-Konfiguration nicht synchronisiert wurde."""
    # Component-Filter: erstes Pfadsegment ist die Component (main, contrib, …)
    if component_set is not None:
        m = _COMPONENT_PREFIX.match(filename)
        if m and m.group(1) not in component_set:
            return True

    # Source-Filter: source/-Verzeichnis nur bei deb-src vorhanden
    if not include_sources and '/source/' in filename:
        return True

    # Architektur-Filter: binary-{arch}/ und Contents-{arch}
    if arch_set is not None:
        m = _ARCH_IN_PATH.search(filename)
        if m and m.group(1) not in arch_set:
            return True
        m = _ARCH_IN_NAME.search(filename)
        if m and m.group(1) not in arch_set:
            return True

    return False


def _check_release_file(
    release_path: Path,
    architectures: list[str] | None = None,
    components: list[str] | None = None,
    include_sources: bool = True,
) -> tuple[bool, list[str]]:
    """Parst eine InRelease-Datei und prüft alle darin referenzierten Dateien.

    Dateien für nicht-konfigurierte Architekturen, Components oder Source-Pakete
    werden übersprungen, da refrapt sie nie heruntergeladen hat.
    """
    issues: list[str] = []
    if not release_path.exists():
        return False, [f"InRelease nicht gefunden: {release_path}"]

    base_dir = release_path.parent
    try:
        content = release_path.read_text(errors="replace")
    except Exception as e:
        return False, [f"Lesefehler: {e}"]

    arch_set: set[str] | None = set(architectures) if architectures else None
    component_set: set[str] | None = set(components) if components else None

    in_block = False
    checked = 0
    for line in content.splitlines():
        if line.startswith(("SHA256:", "SHA512:", "MD5Sum:")):
            in_block = True
            continue
        if in_block:
            if not line.startswith(" "):
                in_block = False
                continue
            parts = line.strip().split()
            if len(parts) < 3:
                continue
            _checksum, size_str, filename = parts[0], parts[1], parts[2]

            if _should_skip(filename, arch_set, component_set, include_sources):
                continue

            file_path = base_dir / filename
            if not file_path.exists():
                issues.append(f"Fehlende Datei: {filename}")
                continue
            try:
                actual_size = file_path.stat().st_size
                expected_size = int(size_str)
                if actual_size != expected_size:
                    issues.append(
                        f"Größe stimmt nicht: {filename} "
                        f"(erwartet {expected_size}, gefunden {actual_size})"
                    )
            except (ValueError, OSError):
                pass
            checked += 1
            if checked >= 500:
                break

    return len(issues) == 0, issues


def validate_repo(repo: dict) -> dict:
    """Validiert einen Repo-Eintrag; gibt {'status', 'issues', 'checked_suites'} zurück."""
    from astrapi_mirror._paths import mirror_path

    if repo.get("is_flat"):
        return {"status": "ok", "issues": [], "checked_suites": 0}

    url = (repo.get("url") or "").rstrip("/")
    host_path = _host_path_from_url(url)
    mirror_base = mirror_path() / host_path

    suites = [s.strip() for s in (repo.get("suites") or []) if s.strip()]
    archs = [a.strip() for a in (repo.get("architectures") or []) if a.strip()]
    comps = [c.strip() for c in (repo.get("components") or []) if c.strip()]
    include_sources = repo.get("repo_type", "deb") == "deb-src"
    all_issues: list[str] = []
    checked = 0

    for suite in suites:
        release_path = mirror_base / "dists" / suite / "InRelease"
        ok, issues = _check_release_file(
            release_path,
            architectures=archs or None,
            components=comps or None,
            include_sources=include_sources,
        )
        all_issues.extend(issues)
        checked += 1

    status = "ok" if not all_issues else "error"
    return {"status": status, "issues": all_issues, "checked_suites": checked}


def validate_all(repos: list[dict]) -> dict[str, dict]:
    """Validiert alle Repos; gibt {repo_id: result} zurück."""
    return {
        repo["id"]: validate_repo(repo)
        for repo in repos
        if repo.get("enabled", True)
    }


# ---------------------------------------------------------------------------
# DEB822-.sources-Snippet
# ---------------------------------------------------------------------------

def client_sources_file(repo: dict, base_url: str) -> str:
    """Erzeugt den Inhalt einer DEB822 .sources-Datei für apt.

    Format (Beispiel):
        Types: deb
        URIs: https://mirror.example.com/repo/debian/caddy
        Suites: bookworm
        Components: main
        Architectures: amd64 arm64
        Signed-By: /etc/apt/trusted.gpg.d/caddy.gpg
    """
    base_url = base_url.rstrip("/")
    repo_id = repo.get("id", "")
    mirror_url = f"{base_url}/repo/debian/{repo_id}"

    lines: list[str] = [f"Types: {repo.get('repo_type', 'deb')}"]

    if repo.get("is_flat"):
        lines.append(f"URIs: {mirror_url}/")
        lines.append("Suites: ./")
    else:
        suites = [s.strip() for s in (repo.get("suites") or []) if s.strip()]
        components = [c.strip() for c in (repo.get("components") or []) if c.strip()]
        lines.append(f"URIs: {mirror_url}")
        if suites:
            lines.append(f"Suites: {' '.join(suites)}")
        if components:
            lines.append(f"Components: {' '.join(components)}")

    archs = [a.strip() for a in (repo.get("architectures") or []) if a.strip()]
    if archs:
        lines.append(f"Architectures: {' '.join(archs)}")

    if repo.get("gpg_key"):
        lines.append(f"Signed-By: /etc/apt/trusted.gpg.d/{repo_id}.gpg")

    return "\n".join(lines) + "\n"
