label:          Arch Linux Repos
nav_group:      Arch Linux
nav_default:    true
settings_button: false

card_actions:
  - type: run
    url:  /ui/archlinux/{item}/sync
  - type: info
    url:  /ui/archlinux/{item}/info
  - type: log
    url:  /api/archlinux/{item}/logs
