label:          Debian Repos
nav_group:      Debian
nav_default:    true
settings_button: false

card_actions:
  - type: run
    url:  /ui/debian/{item}/sync
  - type: info
    url:  /ui/debian/{item}/info
  - type: log
    url:  /api/debian/{item}/logs
